server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url:      jdbc:mysql://35.198.174.32:3306/RELOVSKY
    username: relovsky
    password: relovsky

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh
